export const GroupData = () => [
  {
    name: "Franklin Foodies",
    location: "Franklin, Massachusetts",
    type: "Community",
    member_count: 1250,
    privacy: "Private",
  },
  {
    name: "Bellingham Bookworms",
    location: "Bellingham, Massachusetts",
    type: "Community",
    member_count: 800,
    privacy: "Private",
  },
  {
    name: "Medfield Makerspace",
    location: "Medfield, Massachusetts",
    type: "Community",
    member_count: 1800,
    privacy: "Private",
  },
  {
    name: "Walpole Gardeners Club",
    location: "Walpole, Massachusetts",
    type: "Community",
    member_count: 1500,
    privacy: "Private",
  },
  {
    name: "Foxborough Fitness Fanatics",
    location: "Foxborough, Massachusetts",
    type: "Community",
    member_count: 2200,
    privacy: "Private",
  },
  {
    name: "Concord History Buffs",
    location: "Concord, Massachusetts",
    type: "Community",
    member_count: 1100,
    privacy: "Private",
  },
  {
    name: "Lexington Historical Society",
    location: "Lexington, Massachusetts",
    type: "Community",
    member_count: 900,
    privacy: "Private",
  },
  {
    name: "Newton Book Club",
    location: "Newton, Massachusetts",
    type: "Community",
    member_count: 1400,
    privacy: "Private",
  },
  {
    name: "Brookline Birdwatchers",
    location: "Brookline, Massachusetts",
    type: "Community",
    member_count: 750,
    privacy: "Private",
  },
  {
    name: "Somerville Gardeners Guild",
    location: "Somerville, Massachusetts",
    type: "Community",
    member_count: 1000,
    privacy: "Private",
  },
  {
    name: "Cambridge Film Enthusiasts",
    location: "Cambridge, Massachusetts",
    type: "Community",
    member_count: 1600,
    privacy: "Private",
  },
  {
    name: "Quincy Chess Club",
    location: "Quincy, Massachusetts",
    type: "Community",
    member_count: 800,
    privacy: "Private",
  },
  {
    name: "Boston Running Club",
    location: "Boston, Massachusetts",
    type: "Community",
    member_count: 2500,
    privacy: "Private",
  },
  {
    name: "Waltham Art Society",
    location: "Waltham, Massachusetts",
    type: "Community",
    member_count: 1200,
    privacy: "Private",
  },
  {
    name: "Salem Historical Reenactors",
    location: "Salem, Massachusetts",
    type: "Community",
    member_count: 1300,
    privacy: "Private",
  },
];
